### ISSUE TITLE
Cannot build hode-vs

### ISSUE THREAD

**Issue by CommonLoon102** [beefviper/XMLGameEngine#21]
Hello,

In the hode-vs repo (https://github.com/beefviper/hode-vs) the issues are disabled, so I can't open this there.
Is that still a WIP or it should be possible to compile it with VS?

Based on the instructions, I got stuck at generating the .sln file, because with that toolchain file CMake cannot find SDL2 based on the instructions. Vcpkg's toolchain by default is there: `[path to vcpkg]/scripts/buildsystems/vcpkg.cmake`.
For vcpkg I followed the instructions here: https://github.com/microsoft/vcpkg/tree/2020.11-1#quick-start-windows
I have Windows 7 64 bit and VS 2019 Community  16.9.2.

Then I tried to generate the .sln with CMake GUI by providing `SDL2_DIR` and `DIRENT_INCLUDE_DIRS` and that finally worked with some errors, but VS can't build the solution (`LNK1104	cannot open file 'SDL2::SDL2.lib'`).
I downloaded `SDL2-devel-2.0.10-VC.zip` from its official page, extracted somewhere and used this `sdl2-config.cmake` I found somewhere:
```
set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

# Support both 32 and 64 bit builds
if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
  set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2main.lib")
else ()
  set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2main.lib")
endif ()

string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
```
I put this .cmake file into the correct folder (\lib), then provided this folder in `SDL2_DIR`, then CMake GUI didn't complain anymore about SDL2 when I clicked configure. But it still complains after I click generate.

> CMake Error at CMakeLists.txt:23 (add_executable):
>   Target "hode" links to target "SDL2::SDL2" but the target was not found.
>   Perhaps a find_package() call is missing for an IMPORTED target, or an
>   ALIAS target is missing?

For `DIRENT_INCLUDE_DIRS` I provided `.......=vcpkg/installed/x86-windows/include`, that also solved some errors. VS still didn't find `getopt` when I tried to build, no wonder, it wasn't specified anywhere... So I just deleted all the related code. Still, it failed building the game because `LNK1104	cannot open file 'SDL2::SDL2.lib'`. I've set `Use Vcpkg` to `Yes`. My vcpkg folder is inside the folder where the `CMakeLists.txt` and `.git` are.

Am I missing something or that project is still work in progress?
I'm not that familiar with CMake, I built Raze before, based on GZDoom's instructions, but that worked just fine for the first try.

**Comment by beefviper** [comment]
Sorry about the issues not being opened there. I'm pretty new to all this myself.

hode-vs was a pretty quick hack job to get it to compile on my computer. I tried to make it as generic as possible though.

Are you able to get any other SDL2 applications compiling a cmake project with libraries installed with vcpkg?

Some problems I ran into with vcpkg was not running the integrate command as admin during install... or forgetting to install the right triplet for what I was compiling, like making sure vcpkg compiled the x64 libs too, and not just the 32 bit ones.

I've never run into any of those errors and I'm not really sure what they're trying to say. Like:
"LNK1104 cannot open file 'SDL2::SDL2.lib'" 

I don't even know how that would happen. I don't really know cmake or the other tools that well myself.

I'm sorry I couldn't be of more help.

Good luck though.
